.INCLUDE "ZeroPage/MainZP.asm"
.include "ZeroPage/AudioZP.asm"
.INCLUDE "KongSetup.asm"
.INCLUDE "KongMacros.asm"
.INCLUDE "Audio/KongAPU.asm"
; .INCLUDE "Audio/KongAudio.asm"
.INCLUDE "Input/KongInput.asm"
.INCLUDE "Mappers/KongMMC1.asm"
.INCLUDE "Video/KongPPU.asm"
.INCLUDE "Video/KongRender.asm"
.INCLUDE "Video/KongText.asm"