.space stream_flags                   7
.space stream_note                    7
.space stream_note_length_lo          7
.space stream_note_length_hi          7
.space stream_note_length_counter_lo  7
.space stream_note_length_counter_hi  7
.space stream_instrument_index        7
.space stream_volume_offset           7
.space stream_arpeggio_offset         7
.space stream_pitch_offset            7
.space stream_duty_offset             7

.space stream_channel                 7
.space stream_channel_register_1      7
.space stream_channel_register_2      7
.space stream_channel_register_3      7
.space stream_channel_register_4      7

.space stream_read_address_lo         7
.space stream_read_address_hi         7
.space stream_return_address_lo       7
.space stream_return_address_hi       7

.space stream_tempo_counter_lo        7
.space stream_tempo_counter_hi        7
.space stream_tempo_lo                7
.space stream_tempo_hi                7
